apiVersion: apps.openshift.io/v1
kind: Service
metadata:
  name: barista-service
  annotations:
    description: Barista Service based on Thorntail Runtime
  labels:
    app: barista-service
    expose: 'true'
    group: com.redhat.microservices
    runtime: thorntail
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  selector:
    app: barista-service
    group: com.redhat.microservices
  type: LoadBalancer
