apiVersion: v1
kind: Service
metadata:
  name: barista
  annotations:
    description: Barista Service based on Thorntail Runtime
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    deploymentconfig: barista-service
  type: LoadBalancer
