metadata:
  name: barista-config-file
data:
  barista-config: |
    project:
      stage: staging
    thorntail:
      logging: INFO
      datasources:
        data-sources:
          BaristaDS:
            driver-name: h2
            connection-url: jdbc:h2:mem:barista;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
            user-name: sa
            password: sa
    greeting:
      message: Hello %s from barista-configmap.yml!
