{
 "title": "coffee shop",
 "description": "Coffee Shop Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  {
   "title": "MONEY purchases",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "application_payment_method_counter_total{endpoint=\"http\",job=\"order-service\",namespace=\"microservices-coffeeshop\",payment_method=\"MONEY\",service=\"order-service\"}"
    }
   ]
  },
  {
   "title": "Coffee Storage",
   "type": "gauge",
   "description": "Current coffee beans ammount in grams",
   "gridPos": { "h": 6, "w": 5, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "application_coffee_storage_gauge{endpoint=\"http\",job=\"storage-service\",namespace=\"microservices-coffeeshop\",service=\"storage-service\"}\t"
    }
   ]
  },
  {
   "title": "Milk Storage",
   "type": "gauge",
   "description": "Current milk ammount in mililiters",
   "gridPos": { "h": 6, "w": 5, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "application_milk_storage_gauge{endpoint=\"http\",job=\"storage-service\",namespace=\"microservices-coffeeshop\",service=\"storage-service\"}"
    }
   ]
  },
  {
   "title": "CREDIT_CARD Purchases",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "application_payment_method_counter_total{endpoint=\"http\",job=\"order-service\",namespace=\"microservices-coffeeshop\",payment_method=\"CREDIT_CARD\",service=\"order-service\"}"
    }
   ]
  },
  {
   "title": "Cappuccino's SOLD",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "application_product_counter_total{endpoint=\"http\",job=\"order-service\",namespace=\"microservices-coffeeshop\",service=\"order-service\",type=\"cappuccino\"}\t"
    }
   ]
  },
  {
   "title": "Espresso's SOLD",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "application_product_counter_total{endpoint=\"http\",job=\"order-service\",namespace=\"microservices-coffeeshop\",service=\"order-service\",type=\"espresso\"}\t"
    }
   ]
  },
  {
   "title": "Frappe's SOLD",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 11, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "application_product_counter_total{endpoint=\"http\",job=\"order-service\",namespace=\"microservices-coffeeshop\",service=\"order-service\",type=\"frappe\"}\t"
    }
   ]
  }
 ]
}