apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  namespace: microservices-coffeeshop
spec:
  ingress:
    enabled: true
  config:
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: "123456"
      admin_user: "grafana"
    auth:
      disable_login_form: True
      disable_signout_menu: True
  dashboardLabelSelector:
    - matchExpressions:
        - key: app
          operator: In
          values:
            - grafana
